# -*- coding: utf-8 -*-
"""Copy of DCF2 Historical Analysis - Tyla Lumley.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h2OloEDlYClbsBR1CMBXkNNUGGFhQwln

# DCF Part 2: Historical Analysis

In this notebook, we do historical analysis of our target firm. This is all backward looking.

The primary goal is to help us understand the firm's context which in turn helps us understand how to best make projections into the future. This is not the only analysis we need, but we do need it.

The focus will be on key valuation metrics:
* Growth Rates
* Margins
* Reinvestment

## Plan

1. Get Income Statement data: Revenue and EBIT. Compute growth rates in both for as long a history as we can (4 years for Yahoo)
2. Compute EBIT Margin (EBIT/Revenue) and Gross Margin (Gross Profit/Revenue)
3. Get Balance Sheet data to compute NWC and Change in NWC
4. Get Statement of Cash Flows to get Capital Expenditures and Depreciation & Amortization.
5. Compute Reinvestment = CapEx - D&A + Change in NWC
6. Compute FCF, NOPAT and Reinvestment Rate = Reinvestment/NOPAT


This is our in-class project that we will work on progressively through the mod.

Expectations:
1. Notebook is clean and neat, with no repeated code. It has clearly labeled sections for inputs/imports at the beginning. Code is sufficiently commented to demonstrate your understanding of the code and help you or anyone else who may use this code later. All numbers should be formatted so they are readable (so, use commas with large numbers, only a few decimal points).
2. All calculations are correct and all discussion questions are answered completely but concisely, demonstrating a depth of understanding.

Workflow:
1. Notebooks are inherently experimental and allow you to try things, however that requires some good habits
2. Once you are "done" in any sense, you always need to "clean up" your notebook to make it presentable. You'd do the same in Excel - you've tried lots of things, etc. but before you present it, you clean it up.
3. Finally, restart the Runtime/Kernel and run it cleanly all the way top to bottom one time.

Then, its ready to go.

## 1 Always put Imports and Installs at the beginning

And only put them in once.

Set display options here if you are using them.

Set API Keys here if you need them.
"""

# necessary imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import yfinance as yf

# Format setting for the model - tame the decimals!
pd.reset_option('display.float_format')
pd.set_option('display.float_format', lambda x:'{:,.2f}'.format(x))

# Set Ticker we are modeling
ticker_symbol = 'MSFT'
company_name = 'Microsoft'

eff_tax_rate = 0.19 # need to set Effective Tax Rate, validate
marg_tax_rate = 0.25 # for WACC given

# this is what we divide numbers by, 1000000 is $M
scale_factor = 1000000
scale_name = 'M'

"""## 2 Get Income Statement Data"""

# Create a Ticker object
ticker = yf.Ticker(ticker_symbol)

# Get annual income statement data, transpose and sort so numeric index is in correct order.
# OUTPUT should have 4 rows, one for each date and column names across the top are IS fields
income_statement_df = ticker.income_stmt.T.sort_index()
income_statement_df.head()

# lots of data in this one, so print it out with .info()
income_statement_df.info()

# print key columns: Total Revenue, EBIT, Gross Profit
income_statement_df[['Total Revenue', 'EBIT', 'Gross Profit']]/scale_factor

"""### Compute Growth Rates and Margins"""

from pandas._libs.tslibs.period import IncompatibleFrequency
# Calculate Gross Margin
income_statement_df['Gross Margin'] = income_statement_df['Gross Profit']/income_statement_df['Total Revenue']

# Calculate EBIT Margin
income_statement_df['EBIT Margin'] = income_statement_df['EBIT']/income_statement_df['Total Revenue']

# Compute Revenue Growth, EBIT Growth
income_statement_df['Revenue Growth'] = income_statement_df["Total Revenue"].pct_change()
income_statement_df['EBIT Growth'] = income_statement_df["EBIT"].pct_change()

# Create a dataframe called df_stats that has the following:
# Revenue Growth, EBIT Growth, Gross Margin, EBIT Margin, Tax Rate for Calcs (eff tax rate) - column names. Rows are dates (year)
# How you do this may vary depending on how you did things above
df_stats = income_statement_df[['Revenue Growth', 'EBIT Growth', 'Gross Margin', 'EBIT Margin','Tax Rate For Calcs']].copy()
# print it out
df_stats

"""## 3 Get Balance Sheet Data"""

# Repeat the above but with the balance sheet - get it, transpose so dates are rows, columns are fields
balance_sheet_df = ticker.balance_sheet.T.sort_index()
balance_sheet_df.head()

# again use .info() so you can see what you have
balance_sheet_df.info()

# print key columns for Non-Cash NWC: Current Assets, Current Liabilities, Cash and STI, Current Debt and Capital Leases
balance_sheet_df[['Current Assets', 'Current Liabilities', 'Cash Cash Equivalents And Short Term Investments', 'Current Debt']]/scale_factor

"""### Compute NWC and Change in NWC"""

# Adjust Current Assets by subtracting Cash
balance_sheet_df['Adj CA'] = balance_sheet_df['Current Assets'] - balance_sheet_df['Cash Cash Equivalents And Short Term Investments']

# Adjust Current Liabilities by subtracting Current Debt
balance_sheet_df['Adj CL'] = balance_sheet_df['Current Liabilities'] - balance_sheet_df['Current Debt']

# Calculate NWC = Adj CA - Adj CL
balance_sheet_df['NWC'] = balance_sheet_df['Adj CA'] - balance_sheet_df['Adj CL']

# Calculate the Change in NWC
balance_sheet_df['Ch in NWC'] = balance_sheet_df['NWC'].diff()

# Create a new DataFrame with the required column
nwc_change_df = balance_sheet_df[['NWC', 'Ch in NWC']].copy()

# Display the new DataFrame
nwc_change_df/scale_factor

"""## 4 Get Statement of Cash Flows"""

# Repeat the above but with SCF
cash_flows_df = ticker.cashflow.T.sort_index()

# Reverse the sign of the 'Capital Expenditure' to make it positive (my personal preference - optional)
cash_flows_df['Capital Expenditure'] = -cash_flows_df['Capital Expenditure']

cash_flows_df.head()/scale_factor

# print the .info()
cash_flows_df.info()

# print key columns - CapEx and D&A
cash_flows_df[['Capital Expenditure', 'Depreciation And Amortization']]/scale_factor

# merge cash_flows and nwc_change_df on the date index
merged_cfs = cash_flows_df.join(nwc_change_df)

# Display the merged DataFrame, showing CapEx, D&A and Ch in NWC
merged_cfs[['Capital Expenditure', 'Depreciation And Amortization', 'Ch in NWC']]/scale_factor

"""### Compute Reinvestment and NOPAT"""

# Calculate Reinvestment = CapEx - D&A + Ch in NWC
merged_cfs['Reinvestment'] = merged_cfs['Capital Expenditure'] - merged_cfs['Depreciation And Amortization'] + merged_cfs['Ch in NWC']

# Extract the 'Reinvestment' column to a new DataFrame
reinvestment_df = (merged_cfs[['Reinvestment']].copy())/scale_factor

# Display the 'Reinvestment' DataFrame
reinvestment_df

# Calculate NOPAT in the income statement dataframe
income_statement_df['NOPAT'] = income_statement_df['EBIT']*(1-df_stats['Tax Rate For Calcs'])

# Extract the 'NOPAT' column to a new DataFrame
nopat_df = income_statement_df[['NOPAT']].copy()/scale_factor

# merge in nopat_df and reinvestment_df (I kept it all in nopat_df)
nopat_df = pd.merge(nopat_df, reinvestment_df, left_index=True, right_index=True)

# Display the 'NOPAT' DataFrame
nopat_df

"""## 5 Compute Reinvestment Rate"""

# Calculate Reinvestment Rate = Reinvestment/NOPAT
reinvestment_rate = reinvestment_df['Reinvestment']/income_statement_df['NOPAT']

# compute reinvestment rate
nopat_df['Reinvestment Rate']= nopat_df['Reinvestment']/nopat_df['NOPAT']

# Now, let's display the updated DataFrame with all the required information
nopat_df

"""## 6 Final Result"""

# now merge in the new Reinvestment Rate column into df_stats
df_stats = pd.merge(df_stats, nopat_df[['Reinvestment Rate']], left_index=True, right_index=True)

df_stats



"""## Homework

Compute EBITDA Margin

Output is a dataframe with a column called "EBITDA Margin" (there can be other columns also, but be sure to show this one by itself)
"""

# Compute EBITDA Margin
income_statement_df['EBITDA Margin'] = income_statement_df['EBITDA'] / income_statement_df['Total Revenue']

# Display EBITDA Margin
display(income_statement_df[['EBITDA Margin']])